### ISSUE TITLE
try: card layout

### ISSUE THREAD

**Issue by metaist** [metaist/metaist.com#13]
Now that we have #12, maybe the home page could have a bit more of a card layout?

This is just an experiment, and I'll abandon it if it seems like too much.

**Comment by metaist** [comment]
I kinda got this working:

```less
.posts {
  display: flex;
  flex-wrap: wrap;
  flex-basis: 0;
  justify-content: space-between;
  word-wrap: break-word;
  max-width: 100%;

  .post {
    display: flex;
    flex-direction: column;
    border: 1px solid #ccc;
    border-radius: 8px;
    overflow: hidden;
    margin-bottom: 1rem;
    max-width: 300px;

    img {
      width: 100%;
      height: auto;
      display: block;
      // max-height: 157px;
      min-height: 300px;
      object-fit: cover;
    }

    .metadata {
      padding: 16px;
    }

    .description {
      font-size: 0.9rem;
    }

    time {
      font-size: 0.8rem;
    }

    span.draft {
      .draft-banner;
      border-radius: 0.1rem;
      font-size: 0.8rem;
      padding: 0 0.2rem;
    }

    a {
      font-size: 1.1rem;
    }
  }
}
```
